spring:
  application:
    name: 论坛系统 # 项目名称
  output:
    ansi:
      enabled: ALWAYS # 配置输出的效果
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false  # 数据库连接串
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver # 数据库连接驱动
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置
  # JSON序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    default-property-inclusion: NON_NULL # 不为null时序列化


server:
  port: 9090 # 自定义的服务端口号


logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss #  日期的显示格式
  level:
    root: info # 日志的默认级别
  #    com.bitejiuyeke.forum: debug # 指定包下的日志级别
  file:
    path: /log/forum_001 # 生产环境的日志目录
#    path: D:/log/bit_forum # 日志保存的路径

# mybatis 相关配置，单独配置，顶格写
mybatis:
  mapper-locations: classpath:mapper/**/*.xml # 指定 xxxMapper.xml的扫描路径

# 项目自定义相关配置
bit-forum:
  login:
    url: sign-in.html  # 未登录状况下强制跳转页面
  index: # 首页配置节点
    board-num: 9  # 首页中显示的版块个数